---
- name: my Test qemu file
  copy:
    src: '{{ ansible_distribution }}/my.sh'
    dest: '{{domain_dir}}/src/'
    owner: '{{ansible_user}}'
    group: '{{ansible_user}}'
    mode: a+x

- name: Full virsrh xml Definition
  copy:
    src: '{{item}}.kvm'
    dest: '{{domain_dir}}/'
    owner: '{{ansible_user}}'
    group: '{{ansible_user}}'
    mode: a+x
  with_items:
    - install
