---
- name: Create domains directory
  become: true
  file:
    path: '{{domain_dir}}/src'
    state: directory
    owner: '{{user}}'
    group: '{{user}}'

- git:
    repo: '{{macvm_src.repo.main}}'
    dest: '{{ domain_dir }}/src'
    version: '{{macvm_src.release.works.hash}}'
